spring:
  thymeleaf:
    cache: false
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    show-sql: true
    globally_quoted_identifiers: true

  datasource:
    dbcp2:
      driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/godsaeng
    username: root
    password: root

  servlet:
    multipart:
      location: C:\Users\Harc\Desktop\Backend\GodSaeng\src\main\resources\static\img\challengeimg
      enabled: true
      max-request-size: 30MB
      max-file-size: 10MB

com:
  planner:
    godsaeng:
      upload:
        path: C:\Users\Harc\Desktop\Backend\GodSaeng\src\main\resources\static\img\challengeimg

frontend:
  base:
    url: http://localhost:3000


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

server:
  frontEnd: ${FRONT_END}
  backEnd: ${BACK_END}

  port: 8070

jwt:
  secret-key: ssh34kyh19jhj77
  expire-seconds:
    access-token: 3600
    refresh-token: 30240000
  header:
    access-token: Authorization
    refresh-token: Authorization-refresh