spring:
  thymeleaf:
    cache: false
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    show-sql: true
    globally_quoted_identifiers: true

  datasource:
    dbcp2:
      driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://godsaengdb.cpvbdgo8npm2.ap-northeast-2.rds.amazonaws.com:3306/godsaeng
    username: root
    password: rkdtlstjd

  servlet:
    multipart:

      location: /home/ubuntu/godsaeng/postimg

      enabled: true
      max-request-size: 30MB
      max-file-size: 10MB
      
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
          kakao:
            client-id: 87c054c34eca4ca3541ab083e086cd12
            client-secret: vh89sp3zQwctgfvWcWM7ZTxPGhvhNnSh
            redirect-uri: http://13.125.99.177:8070/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_image
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

com:
  planner:
    godsaeng:
      upload:
        path: /home/ubuntu/godsaeng/postimg
        additionalPath: /home/ubuntu/godsaeng/postimg

frontend:
  base:
    url: https://frontend-inky-pi.vercel.app

server:
  frontEnd: https://frontend-inky-pi.vercel.app
  backEnd: http://13.125.99.177:8070
  port: 8070

jwt:
  secret-key: ssh34kss05kyh19jhj77ntg99lmh02yj
  expire-seconds:
    access-token: 3600
    refresh-token: 30240000
  header:
    access-token: Authorization
    refresh-token: Authorization-refresh
    