spring:
  thymeleaf:
    cache: false
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    show-sql: true
    globally_quoted_identifiers: true

  datasource:
    dbcp2:
      driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/godsaeng
    username: root
    password: root

  servlet:
    multipart:
      location: C:\Users\Harc\Desktop\Backend\GodSaeng\src\main\resources\static\img\challengeimg
      enabled: true
      max-request-size: 30MB
      max-file-size: 10MB
      
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
          kakao:
            client-id: 87c054c34eca4ca3541ab083e086cd12
            client-secret: vh89sp3zQwctgfvWcWM7ZTxPGhvhNnSh
            redirect-uri: http://localhost:8070/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname
            client-name: Kakao
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id

com:
  planner:
    godsaeng:
      upload:
        path: C:\Users\Harc\Desktop\Backend\GodSaeng\src\main\resources\static\img\challengeimg

frontend:
  base:
    url: http://localhost:3000

server:
  frontEnd: ${FRONT_END}
  backEnd: ${BACK_END}
  port: 8070

jwt:
  secret-key: ssh34kss05kyh19jhj77ntg99lmh02yjcorp
  expire-seconds:
    access-token: 3600
    refresh-token: 30240000
  header:
    access-token: Authorization
    refresh-token: Authorization-refresh